title: Default Page

columns:
  - width: 2/3
    sections:
      content:
        type: fields
        fields:
        # Define the fields for the content section here

  - width: 1/3
    sections:
      images: sections/side-images
      gif:    sections/side-gif
      videos: sections/side-videos # This will bring in all the sections defined in allfiles.yml
      files:  sections/side-files  # This will bring in all the sections defined in allfiles.yml
